server:
  port: 8888
  servlet:
    context-path: /console

management:
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: ALWAYS

spring:
  application:
    name: console
  boot:
    admin:
      context-path: /admin
      discovery:
        ignored-services: consul,console
