version: '3.8'
services:
  postgres-quarkus-reactive:
    image: postgres:12
    environment:
      POSTGRES_USER: quarkus_test
      POSTGRES_PASSWORD: quarkus_test
      POSTGRES_DB: quarkus_test
    ports:
      - 5432:5432
