server.port: ${jupiter.applications.consumer.port}

spring:
  config.import: classpath:config/profile-groups.yml
  application.name: ${jupiter.applications.consumer.name}
  profiles.active: local
  security.oauth2.client:
    provider:
      keycloak:
        issuer-uri: ${jupiter.security.oauth2.url}
    registration:
      consumer-client:
        provider: keycloak
        client-id: ${jupiter.applications.consumer.client-id}
        client-secret: ${jupiter.applications.consumer.client-secret}
        authorization-grant-type: client_credentials
        scope: position
