server:
  port: 8585
  servlet:
    context-path: /cube
    path: "/*"

management:
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: ALWAYS

spring:
  application:
    name: cube
