version: '3'
services:
  odfe-master:
    image: amazon/opendistro-for-elasticsearch:1.9.0
    container_name: odfe-master
    environment:
      - cluster.name=odfe-cluster
      - node.name=odfe-master
      - node.master=true
      - node.data=false
      - node.ingest=false
      - discovery.seed_hosts=odfe-master
      - cluster.initial_master_nodes=odfe-master
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - network.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 4G
      restart_policy:
        condition: any
    volumes:
      - odfe-master:/usr/share/elasticsearch/data
      #      - ./es-certif/root-ca.pem:/usr/share/elasticsearch/config/root-ca.pem
      #      - ./es-certif/node.pem:/usr/share/elasticsearch/config/node.pem
      #      - ./es-certif/node-key.pem:/usr/share/elasticsearch/config/node-key.pem
      #      - ./es-certif/admin.pem:/usr/share/elasticsearch/config/admin.pem
      #      - ./es-certif/admin-key.pem:/usr/share/elasticsearch/config/admin-key.pem
      #      - ./es-config/custom-elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      #      - ./es-config/custom-security-config.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/config.yml
      - ./es-config/internal_users.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml
      - ./es-config/roles_mapping.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles_mapping.yml
      - ./es-config/tenants.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/tenants.yml
      - ./es-config/roles.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles.yml
      - ./es-config/action_groups.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/action_groups.yml
    expose:
      - 9200
      - 9300
      - 9600

  odfe-data1:
    image: amazon/opendistro-for-elasticsearch:1.9.0
    container_name: odfe-data1
    environment:
      - cluster.name=odfe-cluster
      - node.name=odfe-data1
      - node.master=false
      - node.data=true
      - node.ingest=true
      - discovery.seed_hosts=odfe-master
      - cluster.initial_master_nodes=odfe-master
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - network.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 4G
      restart_policy:
        condition: any
    volumes:
      - odfe-data1:/usr/share/elasticsearch/data
    expose:
      - 9200
      - 9300
      - 9600

  odfe-data2:
    image: amazon/opendistro-for-elasticsearch:1.9.0
    container_name: odfe-data2
    environment:
      - cluster.name=odfe-cluster
      - node.name=odfe-data2
      - node.master=false
      - node.data=true
      - node.ingest=true
      - discovery.seed_hosts=odfe-master
      - cluster.initial_master_nodes=odfe-master
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - network.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 4G
      restart_policy:
        condition: any
    volumes:
      - odfe-data2:/usr/share/elasticsearch/data
    expose:
      - 9200
      - 9300
      - 9600

  odfe-coordinating:
    image: amazon/opendistro-for-elasticsearch:1.9.0
    container_name: odfe-coordinating
    environment:
      - cluster.name=odfe-cluster
      - node.name=odfe-coordinating
      - node.master=false
      - node.data=false
      - node.ingest=false
      - discovery.seed_hosts=odfe-master
      - cluster.initial_master_nodes=odfe-master
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - network.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 4G
      restart_policy:
        condition: any
    volumes:
      - odfe-coordinating:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
      - 9600:9600

  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:1.9.0
    container_name: odfe-kibana
    environment:
      ELASTICSEARCH_HOSTS: https://odfe-coordinating:9200
    deploy:
      resources:
        limits:
          memory: 2G
      restart_policy:
        condition: any
    #    volumes:
    #      - ./custom-kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:7.8.1
    container_name: logstash
    deploy:
      resources:
        limits:
          memory: 2G
      restart_policy:
        condition: any
    volumes:
      - ./logstash-config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    #      - ./logstash-config/custom-logstash.yml:/usr/share/logstash/config/logstash.yml
    ports:
      - 5000:5000
      - 5000:5000/udp
      - 5001:5001
    environment:
      - INPUT_TCP_PORT=5000
      - INPUT_UDP_PORT=5000
      - INPUT_HTTP_PORT=5001
      - ELASTICSEARCH_HOST1=odfe-data1
      - ELASTICSEARCH_PORT1=9200
      - ELASTICSEARCH_HOST2=odfe-data2
      - ELASTICSEARCH_PORT2=9200

volumes:
  odfe-master:
    external: true
  odfe-data1:
    external: true
  odfe-data2:
    external: true
  odfe-coordinating:
    external: true

networks:
  default:
    external:
      name: odfe-network-cluster
