spring:
  config.activate.on-profile: local
  profiles:
    group:
      "local": "consul"

jupiter:
  security:
    oauth2:
      url: http://localhost:8080/auth/realms/JupiterR
      user-name-attribute: preferred_username
  applications:
    gateway:
      port: 7777
      url: http://localhost:${jupiter.applications.gateway.port}
    server:
      port: 7070
      url: http://localhost:${jupiter.applications.server.port}
