spring:
  config.activate.on-profile: cloud
  cloud:
    consul:
      enabled: true
      discovery:
        instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.value}
        service-name: ${spring.application.name}
  boot:
    admin:
      discovery:
        enabled: true
