spring.config.activate.on-profile: app-local

jupiter:
  security:
    oauth2:
      url: http://localhost:8080/auth/realms/JupiterR
      user-name-attribute: preferred_username
  applications:
    gateway:
      name: local-spring-gateway
      port: 7777
      url: http://localhost:${jupiter.applications.gateway.port}
    server:
      name: local-spring-server
      port: 7070
      url: http://localhost:${jupiter.applications.server.port}
    client:
      name: local-spring-client
      port: 7071
      url: http://localhost:${jupiter.applications.client.port}
    producer:
      name: local-spring-producer
      port: 7072
      url: http://localhost:${jupiter.applications.producer.port}
    consumer:
      name: local-spring-consumer
      port: 7073
      url: http://localhost:${jupiter.applications.consumer.port}

