debug: false

server.shutdown: graceful

spring:
  config.activate.on-profile: common
  main.banner-mode: off
  lifecycle.timeout-per-shutdown-phase: 20s
  cloud.consul:
    enabled: false
    config.enabled: false
  boot.admin.discovery.enabled: false

# same as default with line number
logging.pattern.console: ${CONSOLE_LOG_PATTERN:-%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%logger:%L){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}

management:
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: ALWAYS

logging.level:
  root: INFO
#  org.springframework: DEBUG
#  org.springframework.boot: TRACE
#  org.springframework.cloud.gateway: DEBUG
#  org.springframework.security: DEBUG
#  org.springframework.messaging: DEBUG
#  io.rsocket: DEBUG

#  reactor.netty: DEBUG
