spring:
  config.activate.on-profile: cloud
  cloud:
    consul:
      enabled: true
      discovery:
        instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.value}
        service-name: ${spring.application.name}
  boot:
    admin:
      discovery:
        enabled: true

jupiter:
  applications:
    gateway:
      url: lb://${jupiter.applications.gateway.name}
    server:
      url: lb://${jupiter.applications.server.name}
    client:
      url: lb://${jupiter.applications.client.name}
    producer:
      url: lb://${jupiter.applications.producer.name}
    consumer:
      url: lb://${jupiter.applications.consumer.name}
