spring:
  config.activate.on-profile: consul
  cloud:
    consul:
      discovery:
        enabled: true
        instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.value}
        service-name: ${spring.application.name}
