spring:
  config.activate.on-profile: app-local
  cloud:
    consul:
      host: 192.168.1.120
      port: 8500
#      path: consul
jupiter:
  security:
    oauth2:
      url: http://192.168.1.120/security/realms/JupiterR
      user-name-attribute: preferred_username
  applications:
    gateway:
      name: local-spring-gateway
      client-id: ${jupiter.applications.gateway.name}
      client-secret: qFjiUgyEsuaQuQhb5zbhso0Da96IDoj5
      port: 7777
      url: http://localhost:${jupiter.applications.gateway.port}
    server:
      name: local-spring-server
      client-id: ${jupiter.applications.server.name}
      client-secret: notdefined
      port: 7070
      url: http://localhost:${jupiter.applications.server.port}
    client:
      name: local-spring-client
      client-id: ${jupiter.applications.client.name}
      client-secret: notdefined
      port: 7071
      url: http://localhost:${jupiter.applications.client.port}
    producer:
      name: local-spring-producer
      client-id: ${jupiter.applications.producer.name}
      client-secret: notdefined
      port: 7072
      url: http://localhost:${jupiter.applications.producer.port}
    consumer:
      name: local-spring-consumer
      client-id: ${jupiter.applications.consumer.name}
      client-secret: 4PbJqjT0wEWtcZSgy0vVHJERYPDg5ctE
      port: 7073
      url: http://localhost:${jupiter.applications.consumer.port}

logging:
  level:
    root: info
    web: info
    org.springframework.cloud.gateway: debug
