spring.profiles.group:
  test:
    - common
    - app-local
    - app-test
  local:
    - common
    - app-local
  local-cloud:
    - common
    - cloud
    - app-local
    - app-cloud
  dev:
    - common
    - app-dev
  dev-cloud:
    - common
    - cloud
    - app-dev
    - app-cloud
