server:
  port: 8787
  servlet:
    path: "/*"

management:
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: ALWAYS

spring:
  application:
    name: content
  datasource:
    url: jdbc:h2:file:./content_service;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
