server.port: ${jupiter.applications.producer.port}

spring:
  config.import: classpath:config/profile-groups.yml
  application.name: ${jupiter.applications.producer.name}
  profiles.active: local
  security.oauth2.resourceserver.jwt.issuer-uri: ${jupiter.security.oauth2.url}

  rsocket.server.port: 7000
