server.port: 7777

spring:
  application.name: spring-gateway
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/JupiterRealm
        registration:
          keycloak:
            client-id: spring-gateway
            client-secret: 21955231-b7e5-4d09-ba08-a0652accf642

logging.level:
  org.springframework.cloud.gateway: DEBUG
  reactor.netty: DEBUG

#management.endpoints.web.exposure.include=prometheus
#management.endpoint.health.show-details=always
#management.metrics.tags.application=spring-kotlin-server

