server.port: ${jupiter.applications.gateway.port}

spring:
  application.name: spring-gateway
  profiles.active: local
  security.oauth2.client:
        provider:
          keycloak:
            issuer-uri: ${jupiter.security-oauth2-url}
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: spring-gateway
            client-secret: 7ce920b9-ea33-461c-bf28-c6791b75d854
            authorization-grant-type: authorization_code
            scope: openid
#            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
  cloud.gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: callme-service
          uri: ${jupiter.applications.server.url}
          predicates:
            - Path=/callme/**
          filters:
            - RemoveRequestHeader=Cookie

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  reactor.netty: DEBUG
