server.port: 7070

spring:
  application.name: spring-server
  security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:8080/auth/realms/JupiterR

logging.level:
  org.springframework.security: DEBUG
  reactor.netty: DEBUG
