server.port: ${jupiter.applications.server.port}

spring:
  application.name: spring-server
  profiles.active: local, consul
  security.oauth2.resourceserver.jwt.issuer-uri: ${jupiter.security.oauth2.url}

logging.level:
  org.springframework.security: DEBUG
  reactor.netty: DEBUG
