debug: false

server:
  port: 8888
  servlet:
    context-path: /console

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /management
  endpoint:
    health:
      show-details: ALWAYS

spring:
  application:
    name: console
  boot:
    admin:
      context-path: /admin
      discovery:
        ignored-services: consul,console
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        serviceName: ${spring.application.name}
        health-check-path: ${server.servlet.context-path}${management.endpoints.web.base-path}/health
