server:
  port: 8585
  servlet:
    context-path: /cube
    path: "/*"

management:
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: ALWAYS

spring:
  application:
    name: cube
  datasource:
    url: jdbc:h2:file:./embedded_content_service;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver


contentServer.remote.api.uri: http://localhost:8787/content
