server.port: ${jupiter.applications.server.port}

spring:
  config.import: classpath:config/profile-groups.yml
  application.name: ${jupiter.applications.server.name}
  profiles.active: local
  security.oauth2.resourceserver.jwt.issuer-uri: ${jupiter.security.oauth2.url}
  boot:
    admin:
      context-path: /admin
      discovery:
        ignored-services: consul
